#pragma once

// #define USE_I2C
#define EE_HANDS

#define RGBLIGHT_DEFAULT_VAL (RGBLIGHT_LIMIT_VAL / 4)
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING

#define MOUSEKEY_DELAY 16
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_TIME_TO_MAX 40

#define MOUSEKEY_WHEEL_DELAY 150
#define MOUSEKEY_WHEEL_INTERVAL 150
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
